version: '3.4'
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=strava
    ports:
      - "3306:3306"
    restart: always

  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://db -schemas=strava -user=root -password=password -connectRetries=60 migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - db